using System.ComponentModel.DataAnnotations;

namespace MentalMetal.Application.Interviews;

/// <summary>
/// Configuration knobs for interview transcript AI analysis.
/// </summary>
public sealed class InterviewAnalysisOptions
{
    public const string SectionName = "InterviewAnalysis";

    /// <summary>
    /// Upper bound on tokens generated by the AI synthesis call. Default 800.
    /// </summary>
    [Range(200, 4000)]
    public int MaxAnalysisTokens { get; set; } = 800;

    /// <summary>
    /// Upper bound on characters in the transcript raw text. Requests exceeding this are
    /// rejected with HTTP 413. Default 16000.
    /// </summary>
    [Range(1000, 200_000)]
    public int MaxPromptChars { get; set; } = 16_000;
}
