using System.ComponentModel.DataAnnotations;

namespace MentalMetal.Application.Briefings;

/// <summary>
/// Configuration knobs for the daily/weekly/1:1-prep briefing feature.
/// </summary>
public sealed class BriefingOptions
{
    public const string SectionName = "Briefing";

    /// <summary>
    /// Local hour (in the user's time zone) before which "today's" briefing is still
    /// considered yesterday's. Default 5 (so a 4 a.m. visit returns yesterday's date).
    /// </summary>
    [Range(0, 23)]
    public int MorningBriefingHour { get; set; } = 5;

    /// <summary>
    /// Maximum age, in hours, of a persisted morning briefing before regeneration is required.
    /// Default 12.
    /// </summary>
    [Range(1, 72)]
    public int MorningBriefingStaleHours { get; set; } = 12;

    /// <summary>
    /// Maximum age, in hours, of a persisted weekly briefing before regeneration is required.
    /// Default 12.
    /// </summary>
    [Range(1, 72)]
    public int WeeklyBriefingStaleHours { get; set; } = 12;

    /// <summary>
    /// Maximum age, in hours, of a persisted 1:1 prep sheet before regeneration is required.
    /// Default 12.
    /// </summary>
    [Range(1, 72)]
    public int OneOnOnePrepStaleHours { get; set; } = 12;

    /// <summary>
    /// Upper bound on tokens generated by the AI synthesis call. Default 1500.
    /// </summary>
    [Range(200, 4000)]
    public int MaxBriefingTokens { get; set; } = 1500;

    /// <summary>
    /// Cap on items per facts section (top commitments, overdue delegations, etc.). Default 5.
    /// </summary>
    [Range(1, 20)]
    public int TopItemsPerSection { get; set; } = 5;
}
