// <auto-generated />
using System;
using MentalMetal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentalMetal.Infrastructure.Migrations
{
    [DbContext(typeof(MentalMetalDbContext))]
    [Migration("20260413235235_AddPasswordHashToUsers")]
    partial class AddPasswordHashToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentalMetal.Domain.Captures.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaptureType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("None");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.PrimitiveCollection<Guid[]>("LinkedInitiativeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("LinkedInitiativeIds");

                    b.PrimitiveCollection<Guid[]>("LinkedPersonIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("LinkedPersonIds");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<Guid[]>("SpawnedCommitmentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("SpawnedCommitmentIds");

                    b.PrimitiveCollection<Guid[]>("SpawnedDelegationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("SpawnedDelegationIds");

                    b.PrimitiveCollection<Guid[]>("SpawnedObservationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("SpawnedObservationIds");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Captures", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.ChatThreads.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("_messages")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("Messages")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("ChatThreads", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Commitments.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCaptureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserId");

                    b.ToTable("Commitments", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Delegations.Delegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DelegatePersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastFollowedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SourceCaptureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DelegatePersonId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("UserId");

                    b.ToTable("Delegations", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Initiatives.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("LinkedPersonIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("LinkedPersonIds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Initiatives", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Initiatives.LivingBrief.PendingBriefUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BriefVersionAtProposal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Proposal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InitiativeId", "Status", "CreatedAt");

                    b.ToTable("PendingBriefUpdates", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Ai.AiTasteBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OperationsUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("AiTasteBudgets", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Captures.Capture", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.Captures.AiExtraction", "AiExtraction", b1 =>
                        {
                            b1.Property<Guid>("CaptureId");

                            b1.Property<decimal>("ConfidenceScore");

                            b1.PrimitiveCollection<string>("Decisions")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RisksIdentified")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("SuggestedInitiativeLinks")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("SuggestedPersonLinks")
                                .IsRequired();

                            b1.Property<string>("Summary")
                                .IsRequired();

                            b1.HasKey("CaptureId");

                            b1.ToTable("Captures");

                            b1.ToJson("AiExtraction");

                            b1.WithOwner()
                                .HasForeignKey("CaptureId");

                            b1.OwnsMany("MentalMetal.Domain.Captures.ExtractedCommitment", "Commitments", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<int>("Direction");

                                    b2.Property<string>("DueDate");

                                    b2.Property<string>("PersonHint");

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.OwnsMany("MentalMetal.Domain.Captures.ExtractedDelegation", "Delegations", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("DueDate");

                                    b2.Property<string>("PersonHint");

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.OwnsMany("MentalMetal.Domain.Captures.ExtractedObservation", "Observations", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("PersonHint");

                                    b2.Property<string>("Tag");

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.Navigation("Commitments");

                            b1.Navigation("Delegations");

                            b1.Navigation("Observations");
                        });

                    b.Navigation("AiExtraction");
                });

            modelBuilder.Entity("MentalMetal.Domain.ChatThreads.ChatThread", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.ChatThreads.ContextScope", "Scope", b1 =>
                        {
                            b1.Property<Guid>("ChatThreadId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("InitiativeId")
                                .HasColumnType("uuid")
                                .HasColumnName("ContextInitiativeId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContextScopeType");

                            b1.HasKey("ChatThreadId");

                            b1.ToTable("ChatThreads");

                            b1.WithOwner()
                                .HasForeignKey("ChatThreadId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalMetal.Domain.Initiatives.Initiative", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.Initiatives.LivingBrief.LivingBrief", "Brief", b1 =>
                        {
                            b1.Property<Guid>("InitiativeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BriefVersion")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("BriefVersion");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("")
                                .HasColumnName("BriefSummary");

                            b1.Property<DateTimeOffset?>("SummaryLastRefreshedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BriefSummaryLastRefreshedAt");

                            b1.Property<string>("SummarySource")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Manual")
                                .HasColumnName("BriefSummarySource");

                            b1.PrimitiveCollection<Guid[]>("SummarySourceCaptureIds")
                                .IsRequired()
                                .HasColumnType("uuid[]")
                                .HasColumnName("BriefSummarySourceCaptureIds");

                            b1.Property<string>("_designDirectionHistory")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("jsonb")
                                .HasColumnName("BriefDesignDirectionHistory")
                                .HasDefaultValueSql("'[]'::jsonb");

                            b1.Property<string>("_keyDecisions")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("jsonb")
                                .HasColumnName("BriefKeyDecisions")
                                .HasDefaultValueSql("'[]'::jsonb");

                            b1.Property<string>("_requirementsHistory")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("jsonb")
                                .HasColumnName("BriefRequirementsHistory")
                                .HasDefaultValueSql("'[]'::jsonb");

                            b1.Property<string>("_risks")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("jsonb")
                                .HasColumnName("BriefRisks")
                                .HasDefaultValueSql("'[]'::jsonb");

                            b1.HasKey("InitiativeId");

                            b1.ToTable("Initiatives", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InitiativeId");
                        });

                    b.OwnsMany("MentalMetal.Domain.Initiatives.Milestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("InitiativeId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsCompleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.Property<DateOnly>("TargetDate")
                                .HasColumnType("date");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("InitiativeId");

                            b1.ToTable("InitiativeMilestones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InitiativeId");
                        });

                    b.Navigation("Brief")
                        .IsRequired();

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("MentalMetal.Domain.People.Person", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.People.CandidateDetails", "CandidateDetails", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CvNotes")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("CandidateDetails_CvNotes");

                            b1.Property<string>("PipelineStatus")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CandidateDetails_PipelineStatus");

                            b1.Property<string>("SourceChannel")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CandidateDetails_SourceChannel");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("MentalMetal.Domain.People.CareerDetails", "CareerDetails", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Aspirations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("CareerDetails_Aspirations");

                            b1.Property<string>("GrowthAreas")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("CareerDetails_GrowthAreas");

                            b1.Property<string>("Level")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("CareerDetails_Level");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("CandidateDetails");

                    b.Navigation("CareerDetails");
                });

            modelBuilder.Entity("MentalMetal.Domain.Users.User", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.Users.AiProviderConfig", "AiProviderConfig", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EncryptedApiKey")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("AiProviderEncryptedApiKey");

                            b1.Property<int?>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("AiProviderMaxTokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AiProviderModel");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AiProviderProvider");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.Password", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HashValue")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("BriefingTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("PreferencesBriefingTime");

                            b1.Property<bool>("LivingBriefAutoApply")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("PreferencesLivingBriefAutoApply");

                            b1.Property<bool>("NotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("PreferencesNotificationsEnabled");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PreferencesTheme");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AiProviderConfig");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash");

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Ai.AiTasteBudget", b =>
                {
                    b.HasOne("MentalMetal.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
