// <auto-generated />
using System;
using MentalMetal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentalMetal.Infrastructure.Migrations
{
    [DbContext(typeof(MentalMetalDbContext))]
    [Migration("20260420063954_V2_FlipCommitmentDirections")]
    partial class V2_FlipCommitmentDirections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentalMetal.Domain.Captures.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioBlobRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("AudioDiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("AudioMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CaptureSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CaptureType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.PrimitiveCollection<Guid[]>("LinkedInitiativeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("LinkedInitiativeIds");

                    b.PrimitiveCollection<Guid[]>("LinkedPersonIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("LinkedPersonIds");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("SpawnedCommitmentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("SpawnedCommitmentIds");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TranscriptionFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TranscriptionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NotApplicable");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Captures", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Commitments.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("High");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCaptureId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourceEndOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceStartOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceCaptureId");

                    b.HasIndex("UserId");

                    b.ToTable("Commitments", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Initiatives.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutoSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSummaryRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Initiatives", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Aliases");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.PersonalAccessTokens.PersonalAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("TokenLookupPrefix")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TokenLookupPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalAccessTokens", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Ai.AiTasteBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OperationsUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("AiTasteBudgets", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MentalMetal.Domain.Captures.Capture", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.Captures.AiExtraction", "AiExtraction", b1 =>
                        {
                            b1.Property<Guid>("CaptureId");

                            b1.PrimitiveCollection<string>("Decisions")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("ExtractedAt");

                            b1.PrimitiveCollection<string>("Risks")
                                .IsRequired();

                            b1.Property<string>("Summary")
                                .IsRequired();

                            b1.HasKey("CaptureId");

                            b1.ToTable("Captures");

                            b1.ToJson("AiExtraction");

                            b1.WithOwner()
                                .HasForeignKey("CaptureId");

                            b1.OwnsMany("MentalMetal.Domain.Captures.ExtractedCommitment", "Commitments", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Confidence");

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<int>("Direction");

                                    b2.Property<DateTimeOffset?>("DueDate");

                                    b2.Property<Guid?>("PersonId");

                                    b2.Property<int?>("SourceEndOffset");

                                    b2.Property<int?>("SourceStartOffset");

                                    b2.Property<Guid?>("SpawnedCommitmentId");

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.OwnsMany("MentalMetal.Domain.Captures.InitiativeTag", "InitiativeTags", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Context");

                                    b2.Property<Guid?>("InitiativeId");

                                    b2.Property<string>("RawName")
                                        .IsRequired();

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.OwnsMany("MentalMetal.Domain.Captures.PersonMention", "PeopleMentioned", b2 =>
                                {
                                    b2.Property<Guid>("AiExtractionCaptureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Context");

                                    b2.Property<Guid?>("PersonId");

                                    b2.Property<string>("RawName")
                                        .IsRequired();

                                    b2.HasKey("AiExtractionCaptureId", "__synthesizedOrdinal");

                                    b2.ToTable("Captures");

                                    b2.WithOwner()
                                        .HasForeignKey("AiExtractionCaptureId");
                                });

                            b1.Navigation("Commitments");

                            b1.Navigation("InitiativeTags");

                            b1.Navigation("PeopleMentioned");
                        });

                    b.OwnsMany("MentalMetal.Domain.Captures.TranscriptSegment", "TranscriptSegments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CaptureId")
                                .HasColumnType("uuid");

                            b1.Property<double>("EndSeconds")
                                .HasColumnType("double precision");

                            b1.Property<Guid?>("LinkedPersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SpeakerLabel")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<double>("StartSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("Id");

                            b1.HasIndex("CaptureId");

                            b1.ToTable("CaptureTranscriptSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaptureId");
                        });

                    b.Navigation("AiExtraction");

                    b.Navigation("TranscriptSegments");
                });

            modelBuilder.Entity("MentalMetal.Domain.Users.User", b =>
                {
                    b.OwnsOne("MentalMetal.Domain.Users.AiProviderConfig", "AiProviderConfig", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EncryptedApiKey")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("AiProviderEncryptedApiKey");

                            b1.Property<int?>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("AiProviderMaxTokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AiProviderModel");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AiProviderProvider");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.Password", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HashValue")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.TranscriptionProviderConfig", "TranscriptionProviderConfig", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EncryptedApiKey")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("TranscriptionProviderEncryptedApiKey");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TranscriptionProviderModel");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("TranscriptionProviderProvider");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MentalMetal.Domain.Users.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("BriefingTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("PreferencesBriefingTime");

                            b1.Property<bool>("LivingBriefAutoApply")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("PreferencesLivingBriefAutoApply");

                            b1.Property<bool>("NotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("PreferencesNotificationsEnabled");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PreferencesTheme");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AiProviderConfig");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("TranscriptionProviderConfig");
                });

            modelBuilder.Entity("MentalMetal.Infrastructure.Ai.AiTasteBudget", b =>
                {
                    b.HasOne("MentalMetal.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
