import { Routes } from '@angular/router';
import { authGuard } from './shared/guards/auth.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login/login.page').then(m => m.LoginPage) },
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.page').then(m => m.DashboardPage), canActivate: [authGuard], data: { title: 'Dashboard' } },
  { path: 'briefings/weekly', loadComponent: () => import('./pages/briefings/weekly-briefing.page').then(m => m.WeeklyBriefingPage), canActivate: [authGuard], data: { title: 'Weekly Briefing' } },
  { path: 'capture', loadComponent: () => import('./pages/captures/captures-list/captures-list.component').then(m => m.CapturesListComponent), canActivate: [authGuard], data: { title: 'Capture' } },
  { path: 'capture/:id', loadComponent: () => import('./pages/captures/capture-detail/capture-detail.component').then(m => m.CaptureDetailComponent), canActivate: [authGuard], data: { title: 'Capture Detail' } },
  { path: 'people', loadComponent: () => import('./pages/people/people-list/people-list.component').then(m => m.PeopleListComponent), canActivate: [authGuard], data: { title: 'People' } },
  { path: 'people/:id', loadComponent: () => import('./pages/people/person-detail/person-detail.component').then(m => m.PersonDetailComponent), canActivate: [authGuard], data: { title: 'Person Detail' } },
  { path: 'initiatives', loadComponent: () => import('./pages/initiatives/initiatives-list/initiatives-list.component').then(m => m.InitiativesListComponent), canActivate: [authGuard], data: { title: 'Initiatives' } },
  { path: 'initiatives/:id', loadComponent: () => import('./pages/initiatives/initiative-detail/initiative-detail.component').then(m => m.InitiativeDetailComponent), canActivate: [authGuard], data: { title: 'Initiative Detail' } },
  { path: 'commitments', loadComponent: () => import('./pages/commitments/commitments-list/commitments-list.component').then(m => m.CommitmentsListComponent), canActivate: [authGuard], data: { title: 'Commitments' } },
  { path: 'commitments/:id', loadComponent: () => import('./pages/commitments/commitment-detail/commitment-detail.component').then(m => m.CommitmentDetailComponent), canActivate: [authGuard], data: { title: 'Commitment Detail' } },
  { path: 'delegations', loadComponent: () => import('./pages/delegations/delegations-list/delegations-list.component').then(m => m.DelegationsListComponent), canActivate: [authGuard], data: { title: 'Delegations' } },
  { path: 'delegations/:id', loadComponent: () => import('./pages/delegations/delegation-detail/delegation-detail.component').then(m => m.DelegationDetailComponent), canActivate: [authGuard], data: { title: 'Delegation Detail' } },
  { path: 'one-on-ones', loadComponent: () => import('./pages/one-on-ones/one-on-ones-list/one-on-ones-list.component').then(m => m.OneOnOnesListComponent), canActivate: [authGuard], data: { title: 'One-on-Ones' } },
  { path: 'observations', loadComponent: () => import('./pages/observations/observations-list/observations-list.component').then(m => m.ObservationsListComponent), canActivate: [authGuard], data: { title: 'Observations' } },
  { path: 'goals', loadComponent: () => import('./pages/goals/goals-list/goals-list.component').then(m => m.GoalsListComponent), canActivate: [authGuard], data: { title: 'Goals' } },
  { path: 'interviews', loadComponent: () => import('./pages/interviews/interviews-pipeline/interviews-pipeline.component').then(m => m.InterviewsPipelineComponent), canActivate: [authGuard], data: { title: 'Interviews' } },
  { path: 'interviews/:id', loadComponent: () => import('./pages/interviews/interview-detail/interview-detail.component').then(m => m.InterviewDetailComponent), canActivate: [authGuard], data: { title: 'Interview Detail' } },
  { path: 'nudges', loadChildren: () => import('./features/nudges/nudges.routes').then(m => m.NUDGES_ROUTES) },
  { path: 'my-queue', loadChildren: () => import('./features/my-queue/my-queue.routes').then(m => m.MY_QUEUE_ROUTES) },
  { path: 'close-out', loadChildren: () => import('./features/daily-close-out/daily-close-out.routes').then(m => m.DAILY_CLOSE_OUT_ROUTES) },
  { path: 'chat', loadComponent: () => import('./pages/global-chat/global-chat.page').then(m => m.GlobalChatPageComponent), canActivate: [authGuard], data: { title: 'Chat' } },
  { path: 'settings', loadComponent: () => import('./pages/settings/settings.page').then(m => m.SettingsPage), canActivate: [authGuard], data: { title: 'Settings' } },
  { path: '**', redirectTo: 'dashboard' },
];
